language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"

os:
  - linux

sudo: false

install:
  - echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
  - bash .ci/travis/install_python.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate test-env
  - pip install coveralls
  - python setup.py install

script: 
  - (cd docs && make html 2> /dev/null)
  - bash .ci/travis/run_travis_test.sh

virtualenv:
  system_site_packages: false

after_success:
  coveralls
