package:
  name: landlab
  version: "1.0.0beta"

source:
  path: ..
  # git_url: https://github.com/landlab/landlab

requirements:
  build:
    - python
    - scipy
    - numpy {{environ.get('NUMPY_VERSION', '')}}
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - sympy
    - pandas
    - cython
    - six
    - pyyaml
    - setuptools

  run:
    - python
    - scipy
    - numpy {{environ.get('NUMPY_VERSION', '')}}
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - sympy
    - pandas
    - cython
    - six
    - pyyaml
    - setuptools

build:
  string: {{ environ.get('BUILD_STR', '') }}
